
USE master
IF EXISTS (SELECT * FROM SYS.DATABASES WHERE NAME = 'MoviesApp')
BEGIN
	ALTER DATABASE MoviesApp SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE MoviesApp;
END
GO

CREATE DATABASE MoviesApp
GO

USE MoviesApp
GO
Create Table Users
(
	userId int IDENTITY(1,1) PRIMARY KEY,
	username varchar(400),
	password varchar(400)
	)
Create Table Movies
(
	mId int IDENTITY(1,1) PRIMARY KEY,
	mImage varchar(400),
	mName varchar(400),
	mDate int,
	mGenre varchar(400),
	mRating int,
	mDuration varchar(400),
	mActors varchar(400),
	mDescription varchar(500),
	mImage1 varchar(400),
	mImage2 varchar(400),
	mUrlVideo varchar(1000)
)
DELETE FROM Movies

Create Table UserLike
(
	userId int,
	filmId int,
	PRIMARY KEY (userId, filmId)
	
)

Insert into Movies( mImage, mName, mDate, mGenre, mRating, mDuration,mImage1, mImage2,  mActors,  mDescription,mUrlVideo)
Values	('https://moviesapi.ir/images/tt0111161_poster.jpg','The Shawshank Redemption','1994','Crime, Drama',9.3,'142 min','https://moviesapi.ir/images/tt0111161_screenshot1.jpg','https://moviesapi.ir/images/tt0111161_screenshot2.jpg','Tim Robbins, Morgan Freeman, Bob Gunton, William Sadler','Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.','<iframe width="100%" height="100%" src="https://www.youtube.com/embed/P9mwtI82k6E?si=Flikk5NBSrgZR21h" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>'),
		('https://moviesapi.ir/images/tt0068646_poster.jpg','The Godfather','1972','Crime, Drama',9.2,'175 min','https://moviesapi.ir/images/tt0068646_screenshot2.jpg','https://moviesapi.ir/images/tt0068646_screenshot3.jpg','Marlon Brando, Al Pacino, James Caan, Richard S. Castellano','The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.','<iframe width="100%" height="100%" src="https://www.youtube.com/embed/w3Wo6QiD3eU?si=7G5A5AYpdlXw99ws" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>'),
		('https://moviesapi.ir/images/tt0071562_poster.jpg','The Godfather: Part II','1974','Crime, Drama',9,'202 min','https://moviesapi.ir/images/tt0071562_screenshot2.jpg','https://moviesapi.ir/images/tt0071562_screenshot3.jpg','Al Pacino, Robert Duvall, Diane Keaton, Robert De Niro','The early life and career of Vito Corleone in 1920s New York is portrayed while his son, Michael, expands and tightens his grip on his crime syndicate stretching from Lake Tahoe, Nevada to pre-revolution 1958 Cuba','<iframe width="100%" height="100%" src="https://www.youtube.com/embed/9O1Iy9od7-A?si=g9XCuVLKO01DvKnN" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>'),
		('https://moviesapi.ir/images/tt0468569_poster.jpg','The Dark Knight','2008','Action, Crime, Drama',9,'151 min','https://moviesapi.ir/images/tt0468569_screenshot1.jpg','https://moviesapi.ir/images/tt0468569_screenshot2.jpg','Christian Bale, Heath Ledger, Aaron Eckhart, Michael Caine','When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, the caped crusader must come to terms with one of the greatest psychological tests of his ability to fight injustice.','<iframe width="100%" height="100%" src="https://www.youtube.com/embed/EXeTwQWrcwY?si=QoZepx3AMwGpiSlS" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>'),
		('https://moviesapi.ir/images/tt0050083_poster.jpg','12 Angry Men','1957','Crime',8.9,'96 min','https://moviesapi.ir/images/tt0050083_screenshot1.jpg','https://moviesapi.ir/images/tt0050083_screenshot2.jpg','Martin Balsam, John Fiedler, Lee J. Cobb, E.G. Marshall','A jury holdout attempts to prevent a miscarriage of justice by forcing his colleagues to reconsider the evidence.','<iframe width="100%" height="100%" src="https://www.youtube.com/embed/TEN-2uTi2c0?si=W47pZWJRLZcI6BgJ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>'),
		('https://moviesapi.ir/images/tt0108052_poster.jpg','Schindlers List','1993','Biography',8.9,'195 min','https://moviesapi.ir/images/tt0108052_screenshot1.jpg','https://moviesapi.ir/images/tt0108052_screenshot2.jpg','Liam Neeson, Ben Kingsley, Ralph Fiennes, Caroline Goodall','In German-occupied Poland during World War II, Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazi Germans.','<iframe width="100%" height="100%" src="https://www.youtube.com/embed/mxphAlJID9U?si=vp4Ow58WAMRW5rKG" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>'),
		('https://moviesapi.ir/images/tt0110912_poster.jpg','Pulp Fiction','1994','Crime',8.9,'154 min','https://moviesapi.ir/images/tt0110912_screenshot1.jpg','https://moviesapi.ir/images/tt0110912_screenshot2.jpg','Tim Roth, Amanda Plummer, Laura Lovelace, John Travolta','The lives of two mob hit men, a boxer, a gangsters wife, and a pair of diner bandits intertwine in four tales of violence and redemption.','<iframe width="100%" height="100%" src="https://www.youtube.com/embed/tGpTpVyI_OQ?si=6_SDe6giwVNxKr7D" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>'),
		('https://moviesapi.ir/images/tt0167260_poster.jpg','The Lord of the Rings: The Return of the King','2003','Adventure',8.9,'201 min','https://moviesapi.ir/images/tt0167260_screenshot1.jpg','https://moviesapi.ir/images/tt0167260_screenshot2.jpg','Noel Appleby, Ali Astin, Sean Astin, David Aston','Gandalf and Aragorn lead the World of Men against Saurons army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.','<iframe width="100%" height="100%" src="https://www.youtube.com/embed/r5X-hFf6Bwo?si=KsZwB764EKEThpym" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>'),
		('https://moviesapi.ir/images/tt0060196_poster.jpg','The Good, the Bad and the Ugly','1966','Western',8.9,'161 min','https://moviesapi.ir/images/tt0060196_screenshot1.jpg','https://moviesapi.ir/images/tt0060196_screenshot2.jpg','Eli Wallach, Clint Eastwood, Lee Van Cleef, Aldo Giuffrè','A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.','<iframe width="100%" height="100%" src="https://www.youtube.com/embed/WCN5JJY_wiA?si=DQlH9G174bOim6W6" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>'),
		('https://moviesapi.ir/images/tt0137523_poster.jpg','Fight Club','1999','Drama',8,'139 min','https://moviesapi.ir/images/tt0137523_screenshot1.jpg','https://moviesapi.ir/images/tt0137523_screenshot2.jpg','Edward Norton, Brad Pitt, Meat Loaf, Zach Grenier','An insomniac office worker, looking for a way to change his life, crosses paths with a devil-may-care soap maker, forming an underground fight club that evolves into something much, much more.','<iframe width="100%" height="100%" src="https://www.youtube.com/embed/qtRKdVHc-cE?si=v_BptuZ87QbbnWQJ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>'),
		('https://moviesapi.ir/images/tt0120737_poster.jpg','The Lord of the Rings: The Fellowship of the Ring','2001','Adventure',8.8,'178 min','https://moviesapi.ir/images/tt0120737_screenshot1.jpg','https://moviesapi.ir/images/tt0120737_screenshot2.jpg','Alan Howard, Noel Appleby, Sean Astin, Sala Baker','A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle Earth from the Dark Lord Sauron.','<iframe width="100%" height="100%" src="https://www.youtube.com/embed/V75dMMIW2B4?si=obUaCfCvo06P5SyR" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>'),
		('https://moviesapi.ir/images/tt0080684_poster.jpg','Star Wars: Episode V - The Empire Strikes Back','1980','Action',8.8,'124 min','https://moviesapi.ir/images/tt0080684_screenshot1.jpg','https://moviesapi.ir/images/tt0080684_screenshot2.jpg','Mark Hamill, Harrison Ford, Carrie Fisher, Billy Dee Williams','After the rebels have been brutally overpowered by the Empire on their newly established base, Luke Skywalker takes advanced Jedi training with Master Yoda, while his friends are pursued by Darth Vader as part of his plan to capture Luke.','<iframe width="100%" height="100%" src="https://www.youtube.com/embed/JNwNXF9Y6kY?si=nn7KWX_P6vtJd14n" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>'),
		('https://moviesapi.ir/images/tt0109830_poster.jpg','Forrest Gump','1994','Comedy',8.8,'142 min','https://moviesapi.ir/images/tt0109830_screenshot1.jpg','https://moviesapi.ir/images/tt0109830_screenshot2.jpg','Tom Hanks, Rebecca Williams, Sally Field, Michael Conner Humphreys','Forrest Gump, while not intelligent, has accidentally been present at many historic moments, but his true love, Jenny Curran, eludes him.','<iframe width="100%" height="100%" src="https://www.youtube.com/embed/bLvqoHBptjg?si=b0VnwmJ9Q-bETR3B" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>'),
		('https://moviesapi.ir/images/tt1375666_poster.jpg','Inception','2010','Drama',8.8,'148 min','https://moviesapi.ir/images/tt1375666_screenshot1.jpg','https://moviesapi.ir/images/tt1375666_screenshot2.jpg;','Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page, Tom Hardy','A thief, who steals corporate secrets through use of dream-sharing technology, is given the inverse task of planting an idea into the mind of a CEO.','<iframe width="100%" height="100%" src="https://www.youtube.com/embed/YoHD9XEInc0?si=aJy_xS4QtRNl0UZT" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>'),
		('https://moviesapi.ir/images/tt0167261_poster.jpg','The Lord of the Rings: The Two Towers','2002','Drama',8.7,'179 min','https://moviesapi.ir/images/tt0167261_screenshot1.jpg','https://moviesapi.ir/images/tt0167261_screenshot2.jpg','Bruce Allpress, Sean Astin, John Bach, Sala Baker','While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Saurons new ally, Saruman, and his hordes of Isengard.','<iframe width="100%" height="100%" src="https://www.youtube.com/embed/LbfMDwc4azU?si=WNzfb65pLH7VKbQh" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>'),
		('https://moviesapi.ir/images/tt0073486_poster.jpg','One Flew Over the Cuckoos Nest','1975','Drama',8.7,'133 min','https://moviesapi.ir/images/tt0073486_screenshot1.jpg','https://moviesapi.ir/images/tt0073486_screenshot2.jpg','Michael Berryman, Peter Brocco, Dean R. Brooks, Alonzo Brown','A criminal pleads insanity after getting into trouble again and once in the mental institution rebels against the oppressive nurse and rallies up the scared patients.','<iframe width="100%" height="100%" src="https://www.youtube.com/embed/OXrcDonY-B8?si=8Rv3RluW263ADT0w" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>'),
		('https://moviesapi.ir/images/tt0099685_poster.jpg','Goodfellas','1990','Biography',8.7,'146 min','https://moviesapi.ir/images/tt0099685_screenshot1.jpg','https://moviesapi.ir/images/tt0099685_screenshot2.jpg','Robert De Niro, Ray Liotta, Joe Pesci, Lorraine Bracco','Henry Hill and his friends work their way up through the mob hierarchy.','<iframe width="100%" height="100%" src="https://www.youtube.com/embed/2ilzidi_J8Q?si=9a1UE8bZ5KmBBbCV" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>'),
		('https://moviesapi.ir/images/tt0133093_poster.jpg','The Matrix','1999','Action',8.7,'136 min','https://moviesapi.ir/images/tt0133093_screenshot1.jpg','https://moviesapi.ir/images/tt0133093_screenshot2.jpg','Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss, Hugo Weaving','A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.','<iframe width="100%" height="100%" src="https://www.youtube.com/embed/vKQi3bBA1y8?si=AhCEt-48T5sj0mOu" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>'),
		('https://moviesapi.ir/images/tt0076759_poster.jpg','Star Wars: Episode IV - A New Hope','1977','Action',8.7,'121 min','https://moviesapi.ir/images/tt0076759_screenshot1.jpg','https://moviesapi.ir/images/tt0076759_screenshot2.jpg','Mark Hamill, Harrison Ford, Carrie Fisher, Peter Cushing','Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a wookiee and two droids to save the galaxy from the Empires world-destroying battle-station, while also attempting to rescue Princess Leia from the evil Darth Vader','<iframe width="100%" height="100%" src="https://www.youtube.com/embed/vZ734NWnAHA?si=cxtP-qAw4yjy0Uom" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>'),
		('https://moviesapi.ir/images/tt0114369_poster.jpg','Se7en','1995','Crime',8.6,'127 min ','https://moviesapi.ir/images/tt0114369_screenshot1.jpg ','https://moviesapi.ir/images/tt0114369_screenshot2.jpg ','Morgan Freeman, Andrew Kevin Walker, Daniel Zacapa, Brad Pitt ','Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his modus operandi.','<iframe width="100%" height="100%" src="https://www.youtube.com/embed/znmZoVkCjpI?si=l9uUy7vAgIbvPIgy" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>' ),
		('https://moviesapi.ir/images/tt0102926_poster.jpg ','The Silence of the Lambs ','1991','Crime',8.2,'118 min ','https://moviesapi.ir/images/tt0102926_screenshot1.jpg ','https://moviesapi.ir/images/tt0102926_screenshot2.jpg ','Jodie Foster, Lawrence A. Bonney, Kasi Lemmons, Lawrence T. Wrentz ','A young F.B.I. cadet must confide in an incarcerated and manipulative killer to receive his help on catching another serial killer who skins his victims. ','<iframe width="100%" height="100%" src="https://www.youtube.com/embed/6iB21hsprAQ?si=KaikAy0ib4mrCTqZ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe> '),
		('https://moviesapi.ir/images/tt0038650_poster.jpg ','It is a Wonderful Life ','1946 ','Family ',8.6 ,'130 min ','https://moviesapi.ir/images/tt0038650_screenshot1.jpg ','https://moviesapi.ir/images/tt0038650_screenshot2.jpg ','James Stewart, Donna Reed, Lionel Barrymore, Thomas Mitchell ','An angel helps a compassionate but despairingly frustrated businessman by showing what life would have been like if he never existed', '<iframe width="100%" height="100%" src="https://www.youtube.com/embed/iLR3gZrU2Xo?si=zM0zUgdkVPzdajkM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe> '),
		('https://moviesapi.ir/images/tt0114814_poster.jpg ','The Usual Suspects ','1995 ','Mystery ',8.6 ,'106 min ','https://moviesapi.ir/images/tt0114814_screenshot1.jpg ','https://moviesapi.ir/images/tt0114814_screenshot2.jpg ','Stephen Baldwin, Gabriel Byrne, Benicio Del Toro, Kevin Pollak ','A sole survivor tells of the twisty events leading up to a horrific gun battle on a boat, which begin when five criminals meet at a seemingly random police lineup. ','<iframe width="100%" height="100%" src="https://www.youtube.com/embed/x3t0Nc6fg7w?si=Sq9qho0h4I5C4D5I" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe> '),
		('https://moviesapi.ir/images/tt0110413_poster.jpg ','Life Is Beautiful ','1994 ','Comedy ',8.8 ,'110 min','https://moviesapi.ir/images/tt0110413_screenshot1.jpg ','https://moviesapi.ir/images/tt0110413_screenshot2.jpg ','Jean Reno, Gary Oldman, Natalie Portman, Danny Aiello ','Mathilda, a 12-year-old girl, is reluctantly taken in by Léon, a professional assassin, after her family is murdered. Léon and Mathilda form an unusual relationship, as she becomes his protégée and learns the assassins trade. ','<iframe width="100%" height="100%" src="https://www.youtube.com/embed/aNQqoExfQsg?si=1k5_RyJj18Y_AmjY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe> '),
		('https://moviesapi.ir/images/tt0027977_poster.jpg ','Modern Times ','1936 ','Comedy ',8.6 ,'87 min ','https://moviesapi.ir/images/tt0027977_screenshot1.jpg ','https://moviesapi.ir/images/tt0027977_screenshot2.jpg ','Charles Chaplin, Paulette Goddard, Henry Bergman, Tiny Sandford ','The Tramp struggles to live in modern industrial society with the help of a young homeless woman. ','<iframe width="100%" height="100%" src="https://www.youtube.com/embed/GLeDdzGUTq0?si=IVTPY94VKC4JkVG0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe> '),
		('https://moviesapi.ir/images/tt0209144_poster.jpg ','Memento ','2000 ','Mystery,Thriller ',8.9 ,'113 min ','https://moviesapi.ir/images/tt0209144_screenshot1.jpg ','https://moviesapi.ir/images/tt0209144_screenshot2.jpg ','Guy Pearce, Carrie-Anne Moss, Joe Pantoliano, Mark Boone Junio ','A man juggles searching for his wifes murderer and keeping his short-term memory loss from being an obstacle. ','<iframe width="100%" height="100%" src="https://www.youtube.com/embed/4CV41hoyS8A?si=hIICmT8Mi_Q9ZSRL" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe> '),
		('https://moviesapi.ir/images/tt0482571_poster.jpg ','The Prestige ','2006 ','Drama,Mystery,Sci-Fi ',8.6 ,'130 min ','https://moviesapi.ir/images/tt0482571_screenshot1.jpg ','https://moviesapi.ir/images/tt0482571_screenshot2.jpg, ','Hugh Jackman, Christian Bale, Michael Caine, Piper Perabo ','Two stage magicians engage in competitive one-upmanship in an attempt to create the ultimate stage illusion. ','<iframe width="100%" height="100%" src="https://www.youtube.com/embed/RLtaA9fFNXU?si=Yx93_fy-5YAtloHu" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe> '),
		('https://moviesapi.ir/images/tt0090605_poster.jpg ','Aliens ','1986 ','Action,Adventure,Sci-Fi ',8.6 ,'137 min ','https://moviesapi.ir/images/tt0090605_screenshot1.jpg ','https://moviesapi.ir/images/tt0090605_screenshot2.jpg ','Sigourney Weaver, Carrie Henn, Michael Biehn, Paul Reiser ','The moon from Alien (1979) has been colonized, but contact is lost. This time, the rescue team has impressive firepower, but will it be enough? ','<iframe width="100%" height="100%" src="https://www.youtube.com/embed/oSeQQlaCZgU?si=SkMTsY2S7yD2ISxe" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe> '),
		('https://moviesapi.ir/images/tt0087843_poster.jpg ','Once Upon a Time in America ','1984 ','Crime,Drama ',8.6 ,'229 min ','https://moviesapi.ir/images/tt0087843_screenshot1.jpg ','https://moviesapi.ir/images/tt0087843_screenshot2.jpg ','Robert De Niro, James Woods, Elizabeth McGovern, Joe Pesci ','A former Prohibition-era Jewish gangster returns to the Lower East Side of Manhattan over thirty years later, where he once again must confront the ghosts and regrets of his old life. ','<iframe width="100%" height="100%" src="https://www.youtube.com/embed/LcpCRyNo8T8?si=H2051SVDoJ7bfut3" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe> '),
		('https://moviesapi.ir/images/tt0033467_poster.jpg ','Citizen Kane ','1941 ','Drama,Mystery ',8.6 ,'119 min ','https://moviesapi.ir/images/tt0033467_screenshot1.jpg ','https://moviesapi.ir/images/tt0033467_screenshot2.jpg ','Joseph Cotten, Dorothy Comingore, Agnes Moorehead, Ruth Warrick ','Following the death of a publishing tycoon, news reporters scramble to discover the meaning of his final utterance. ','<iframe width="100%" height="100%" src="https://www.youtube.com/embed/8dxh3lwdOFw?si=DQFgpPM6SHERMCIU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe> '),
		('https://moviesapi.ir/images/tt0052357_poster.jpg ','Vertigo ','1958 ','Mystery,Romance,Thriller ',8.6 ,'128 min ','https://moviesapi.ir/images/tt0052357_screenshot1.jpg ','https://moviesapi.ir/images/tt0052357_screenshot2.jpg ','James Stewart, Kim Novak, Barbara Bel Geddes, Tom Helmore ','A San Francisco detective suffering from acrophobia investigates the strange activities of an old friends wife, all the while becoming dangerously obsessed with her. ',' <iframe width="100%" height="100%" src="https://www.youtube.com/embed/Z5jvQwwHQNY?si=7_gDlYPs2Xbe7glx" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>'),
		('https://moviesapi.ir/images/tt0086190_poster.jpg ','Star Wars: Episode VI - Return of the Jedi ','1983 ','Action,Adventure,Fantasy ',8.6 ,'131 min ','https://moviesapi.ir/images/tt0086190_screenshot1.jpg ','https://moviesapi.ir/images/tt0086190_screenshot2.jpg ','Mark Hamill, Harrison Ford, Carrie Fisher, Billy Dee Williams ','After rescuing Han Solo from the palace of Jabba the Hutt, the rebels attempt to destroy the second Death Star, while Luke struggles to make Vader return from the dark side of the Force. ','<iframe width="100%" height="100%" src="https://www.youtube.com/embed/7L8p7_SLzvU?si=1IE8yKFI2UeQRo2g" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe> '),
		('https://moviesapi.ir/images/tt0105236_poster.jpg ','Reservoir Dogs ','1992 ','Crime,Drama,Thriller ',8.6 ,'99 min ','https://moviesapi.ir/images/tt0105236_screenshot1.jpg ','https://moviesapi.ir/images/tt0105236_screenshot2.jpg ','Harvey Keitel, Tim Roth, Michael Madsen, Chris Penn ','After a simple jewelry heist goes terribly wrong, the surviving criminals begin to suspect that one of them is a police informant. ','<iframe width="100%" height="100%" src="https://www.youtube.com/embed/vayksn4Y93A?si=WWOJYQKtckvBmNnC" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe> '),
		('https://moviesapi.ir/images/tt0112573_poster.jpg ','Braveheart ','1996 ','Biography,Drama,History ',8.6 ,'102 min ','https://moviesapi.ir/images/tt0112573_screenshot1.jpg ','https://moviesapi.ir/images/tt0112573_screenshot2.jpg ','James Robinson, Sean Lawlor, Sandy Nelson, James Cosmo ','When his secret bride is executed for assaulting an English soldier who tried to rape her, William Wallace begins a revolt against King Edward I of England. ','<iframe width="100%" height="100%" src="https://www.youtube.com/embed/nMft5QDOHek?si=a4r5fuCaEgc5g-h5" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe> '),
		('https://moviesapi.ir/images/tt0180093_poster.jpg ','Requiem for a Dream ','2000 ','Drama ',8.6 ,'102 min ','https://moviesapi.ir/images/tt0180093_screenshot1.jpg ','https://moviesapi.ir/images/tt0180093_screenshot2.jpg ','Ellen Burstyn, Jared Leto, Jennifer Connelly, Marlon Wayans ','The drug-induced utopias of four Coney Island people are shattered when their addictions run deep ','<iframe width="100%" height="100%" src="https://www.youtube.com/embed/QBwzN4v1vA0?si=tHP_3w4Opg1elASy" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe> '),
		('https://moviesapi.ir/images/tt0066921_poster.jpg ','A Clockwork Orange ','1971 ','Crime,Drama ',8.6 ,'123 min ','https://moviesapi.ir/images/tt0066921_screenshot1.jpg ','https://moviesapi.ir/images/tt0066921_screenshot2.jpg ','Malcolm McDowell, Patrick Magee, Michael Bates, Warren Clarke ','In future Britain, Alex DeLarge, a charismatic and psycopath delinquent, who likes to practice crimes and ultra-violence with his gang, is jailed and volunteers for an experimental aversion therapy developed by the government in an effort to solve societys crime problem - but not all goes according to plan. ','<iframe width="100%" height="100%" src="https://www.youtube.com/embed/T54uZPI4Z8A?si=qi4j6rZ4QYCKjFBE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe> '),
		('https://moviesapi.ir/images/tt0075314_poster.jpg ','Taxi Driver ','1976 ','Crime, Drama ',8.6 ,'113 min ','https://moviesapi.ir/images/tt0075314_screenshot1.jpg ','https://moviesapi.ir/images/tt0075314_screenshot2.jpg ','Diahnne Abbott, Frank Adu, Victor Argo, Gino Ardito ','A mentally unstable Vietnam War veteran works as a night-time taxi driver in New York City where the perceived decadence and sleaze feeds his urge for violent action, attempting to save a preadolescent prostitute in the process ','<iframe width="100%" height="100%" src="https://www.youtube.com/embed/T5IligQP7Fo?si=HAaQICZCSc09RAQ7" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe> '),
		('https://moviesapi.ir/images/tt0056172_poster.jpg ','Lawrence of Arabia ','1981 ','Adventure,Biography,Drama ',8.6 ,'216 min ','https://moviesapi.ir/images/tt0056172_screenshot1.jpg ','https://moviesapi.ir/images/tt0056172_screenshot2.jpg ','Peter OToole, Alec Guinness, Anthony Quinn, Jack Hawkins ','The story of T.E. Lawrence, the English officer who successfully united and lead the diverse, often warring, Arab tribes during World War I in order to fight the Turks. ','<iframe width="100%" height="100%" src="https://www.youtube.com/embed/vOlRhGEhG7k?si=ui9lpjyb-Xu17s6z" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe> '),
		('https://moviesapi.ir/images/tt0056592_poster.jpg ','To Kill a Mockingbird ','1962 ','Crime,Drama ',8.6 ,'129 min ','https://moviesapi.ir/images/tt0056592_screenshot1.jpg, ','https://moviesapi.ir/images/tt0056592_screenshot2.jpg ','Gregory Peck, John Megna, Frank Overton, Rosemary Murphy ','Atticus Finch, a lawyer in the Depression-era South, defends a black man against an undeserved rape charge, and his children against prejudice. ','<iframe width="100%" height="100%" src="https://www.youtube.com/embed/KR7loA_oziY?si=5BzCPHc4qWcZAYqB" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe> '),
		('https://moviesapi.ir/images/tt0110357_poster.jpg ','The Lion King ','1994 ','Animation,Adventure,Drama ',8.6 ,'89 min ','https://moviesapi.ir/images/tt0110357_screenshot1.jpg ','https://moviesapi.ir/images/tt0110357_screenshot2.jpg ','Matthew Broderick, Jonathan Taylor Thomas, James Earl Jones, Jim Cummings ','Lion cub and future king Simba searches for his identity. His eagerness to please others and penchant for testing his boundaries sometimes gets him into trouble. ','<iframe width="100%" height="100%" src="https://www.youtube.com/embed/7TavVZMewpY?si=JDTR4ls2njN7moAZ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe> '),
		('https://moviesapi.ir/images/tt0050825_poster.jpg ','The Lives of Others ','2022 ','Drama,Thriller ',8.9 ,'88 min ','https://moviesapi.ir/images/tt0050825_screenshot2.jpg ','https://moviesapi.ir/images/tt0050825_screenshot1.jpg ','Kirk Douglas, Ralph Meeker, Adolphe Menjou, George Macready ','After refusing to attack an enemy position, a general accuses the soldiers of cowardice and their commanding officer must defend them. ','<iframe width="100%" height="100%" src="https://www.youtube.com/embed/nmDA60X-f_A?si=a-ZdaOHIOqnpw_lP" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe> '),
        ('https://moviesapi.ir/images/tt1853728_poster.jpg ','Django Unchained ','2022 ','Drama,Western ',8.6 ,'165 min ','https://moviesapi.ir/images/tt1853728_screenshot1.jpg ','https://moviesapi.ir/images/tt1853728_screenshot2.jpg ','Jamie Foxx, Christoph Waltz, Leonardo DiCaprio, Kerry Washington ','With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner. ','<iframe width="100%" height="100%" src="https://www.youtube.com/embed/0fUCuvNlOCg?si=yZGrMrrnn0Ji_loZ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe> '),
		('https://moviesapi.ir/images/tt0081505_poster.jpg ','The Shining ','2023 ','Drama,Horror ',8.9 ,'146 min ','https://moviesapi.ir/images/tt0081505_screenshot1.jpg ','https://moviesapi.ir/images/tt0081505_screenshot2.jpg ','Jack Nicholson, Shelley Duvall, Danny Lloyd, Scatman Crothers ','A family heads to an isolated hotel for the winter where an evil and spiritual presence influences the father into violence, while his psychic son sees horrific forebodings from the past and of the future. ','<iframe width="100%" height="100%" src="https://www.youtube.com/embed/S014oGZiSdI?si=JxUSbfVZr3o9VQ3i" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe> '),
		('https://moviesapi.ir/images/tt0910970_poster.jpg ','WALL·E ','2024 ','Animation,Adventure,Family ',9.1 ,'98 min ','https://moviesapi.ir/images/tt0910970_screenshot1.jpg ','https://moviesapi.ir/images/tt0910970_screenshot2.jpg ','Ben Burtt, Elissa Knight, Jeff Garlin, Fred Willard ','In the distant future, a small waste-collecting robot inadvertently embarks on a space journey that will ultimately decide the fate of mankind. ','<iframe width="100%" height="100%" src="https://www.youtube.com/embed/CZ1CATNbXg0?si=q48DCcpRKBH7uao8" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe> '),
		('https://moviesapi.ir/images/tt1345836_poster.jpg ','The Dark Knight Rises ','2023 ','Action,Thriller ',9.4 ,'164 min ','https://moviesapi.ir/images/tt1345836_screenshot1.jpg ','https://moviesapi.ir/images/tt1345836_screenshot2.jpg ','Christian Bale, Gary Oldman, Tom Hardy, Joseph Gordon-Levitt ','Eight years after the Jokers reign of anarchy, the Dark Knight, with the help of the enigmatic Selina, is forced from his imposed exile to save Gotham City, now on the edge of total annihilation, from the brutal guerrilla terrorist Bane. ','<iframe width="100%" height="100%" src="https://www.youtube.com/embed/g8evyE9TuYk?si=EEn39te9O5gbtVF_" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe> '),
		('https://moviesapi.ir/images/tt0169547_poster.jpg ','American Beauty ','2021 ','Drama,Romance ',8.5 ,'122 min ','https://moviesapi.ir/images/tt0169547_screenshot1.jpg ','https://moviesapi.ir/images/tt0169547_screenshot2.jpg ','Kevin Spacey, Annette Bening, Thora Birch, Wes Bentley ','A sexually frustrated suburban father has a mid-life crisis after becoming infatuated with his daughters best friend. ','<iframe width="100%" height="100%" src="https://www.youtube.com/embed/Ly7rq5EsTC8?si=Xh98ga4jQNpNNOhb" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe> '),
	    ('https://moviesapi.ir/images/tt0119698_poster.jpg ','Princess Mononoke ','2023 ','Animation,Adventure,Fantasy ',9.5 ,'134 min ','https://moviesapi.ir/images/tt0119698_screenshot1.jpg ','https://moviesapi.ir/images/tt0119698_screenshot2.jpg ','Billy Crudup, Billy Bob Thornton, Minnie Driver, John DiMaggio ','On a journey to find the cure for a Tatarigamis curse, Ashitaka finds himself in the middle of a war between the forest gods and Tatara, a mining colony. In this quest he also meets San, the Mononoke Hime ','<iframe width="100%" height="100%" src="https://www.youtube.com/embed/4OiMOHRDs14?si=qxmJSpfKCz9Wfpw8" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe> '),
		('https://moviesapi.ir/images/tt0120815_poster.jpg ','Saving Private Ryan ','2021 ','War ',8.6 ,'169 min ','https://moviesapi.ir/images/tt0120815_screenshot1.jpg ','https://moviesapi.ir/images/tt0120815_screenshot2.jpg ','Tom Hanks, Tom Sizemore, Edward Burns, Barry Pepper ','Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action. ','<iframe width="100%" height="100%" src="https://www.youtube.com/embed/9CiW_DgxCnQ?si=pHMA6gLb-lqstfzS" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe> '),
		('https://moviesapi.ir/images/tt0064116_poster.jpg ','Once Upon a Time in the West ','2018 ','Western ',8.6,'175 min ','https://moviesapi.ir/images/tt0064116_screenshot1.jpg ','https://moviesapi.ir/images/tt0064116_screenshot2.jpg ','Claudia Cardinale, Henry Fonda, Jason Robards, Charles Bronson ','A mysterious stranger with a harmonica joins forces with a notorious desperado to protect a beautiful widow from a ruthless assassin working for the railroad. ','<iframe width="100%" height="100%" src="https://www.youtube.com/embed/c8CJ6L0I6W8?si=g5TFAmZkE4u31Yng" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe> '),
		('https://moviesapi.ir/images/tt0120586_poster.jpg ','American History X ','2021 ','Crime ',8.6 ,'119 min ','https://moviesapi.ir/images/tt0120586_screenshot1.jpg ','https://moviesapi.ir/images/tt0120586_screenshot2.jpg ','Edward Norton, Edward Furlong, Beverly DAngelo, Jennifer Lien ','A former neo-nazi skinhead tries to prevent his younger brother from going down the same wrong path that he did. ',' <iframe width="100%" height="100%" src="https://www.youtube.com/embed/XfQYHqsiN5g?si=RX4ZU_O2KwQdTPzN" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>'),
		('https://moviesapi.ir/images/tt0816692_poster.jpg ','Interstellar ','2024 ','Drama ',8.5 ,'169 min ','https://moviesapi.ir/images/tt0816692_screenshot1.jpg ','https://moviesapi.ir/images/tt0816692_screenshot2.jpg ','Ellen Burstyn, Matthew McConaughey, Mackenzie Foy, John Lithgow ','A team of explorers travel through a wormhole in space in an attempt to ensure humanitys survival. ','<iframe width="100%" height="100%" src="https://www.youtube.com/embed/zSWdZVtXT7E?si=IH9YtINW8QjuQaHz" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe> '),
		('https://moviesapi.ir/images/tt0034583_poster.jpg ','Casablanca ','2017 ','Romance ',8.6 ,'102 min','https://moviesapi.ir/images/tt0034583_screenshot1.jpg ','https://moviesapi.ir/images/tt0034583_screenshot2.jpg ','Humphrey Bogart, Ingrid Bergman, Paul Henreid, Claude Rains ','In Casablanca, Morocco in December 1941, a cynical American expatriate meets a former lover, with unforeseen complications. ','<iframe width="100%" height="100%" src="https://www.youtube.com/embed/MF7JH_54d8c?si=h6e4mbLJ3npi7TyP" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe> '),
		('https://moviesapi.ir/images/tt0054215_poster.jpg ','Psycho ','2017 ','Horror ',8.6 ,'109 min ','https://moviesapi.ir/images/tt0054215_screenshot1.jpg ','https://moviesapi.ir/images/tt0054215_screenshot2.jpg ','Anthony Perkins, Vera Miles, John Gavin, Janet Leigh ','A Phoenix secretary embezzles $40,000 from her employers client, goes on the run, and checks into a remote motel run by a young man under the domination of his mother. ','<iframe width="100%" height="100%" src="https://www.youtube.com/embed/NG3-GlvKPcg?si=Ntnz0b2WLeOAJAmS" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe> '),
		('https://moviesapi.ir/images/tt0021749_poster.jpg ','City Lights ','2020 ','Romance ',8.6 ,'87 min ','https://moviesapi.ir/images/tt0021749_screenshot1.jpg ','https://moviesapi.ir/images/tt0021749_screenshot2.jpg ','Virginia Cherrill, Florence Lee, Harry Myers, Al Ernest Garcia ','With the aid of a wealthy erratic tippler, a dewy-eyed tramp who has fallen in love with a sightless flower girl accumulates money to be able to help her medically. ','<iframe width="100%" height="100%" src="https://www.youtube.com/embed/7vl7F8S4cpQ?si=0aln93hshJX8UgUO" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe> '),
		('https://moviesapi.ir/images/tt0120689_poster.jpg ','The Green Mile ','2019 ','Crime ',8.1 ,'189 min ','https://moviesapi.ir/images/tt0120689_screenshot1.jpg ','https://moviesapi.ir/images/tt0120689_screenshot2.jpg ','Tom Hanks, David Morse, Michael Clarke Duncan, Bonnie Hunt ','The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift. ','<iframe width="100%" height="100%" src="https://www.youtube.com/embed/Ki4haFrqSrw?si=g_UkvYlCFHzff8ps" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe> '),
		('https://moviesapi.ir/images/tt0082971_poster.jpg ','Raiders of the Lost Ark ','2023 ','Action ',8.6 ,'115 min ','https://moviesapi.ir/images/tt0082971_screenshot1.jpg ','https://moviesapi.ir/images/tt0082971_screenshot2.jpg ','Harrison Ford, Karen Allen, Paul Freeman, Ronald Lacey ','Archaeologist and adventurer Indiana Jones is hired by the U.S. government to find the Ark of the Covenant before the Nazis ',' <iframe width="100%" height="100%" src="https://www.youtube.com/embed/0xQSIdSRlAk?si=UdsTL2otDXHVIabc" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>'),
		('https://moviesapi.ir/images/tt0103064_poster.jpg ','Terminator 2: Judgment Day ','2021 ','Action,Sci-Fi,Thriller ',8.3 ,'137 min ','https://moviesapi.ir/images/tt0103064_screenshot1.jpg ','https://moviesapi.ir/images/tt0103064_screenshot2.jpg ','Arnold Schwarzenegger, Linda Hamilton, Edward Furlong, Robert Patrick ','A cyborg, identical to the one who failed to kill Sarah Connor, must now protect her young son, John Connor, from a more advanced cyborg, made out of liquid metal. ','<iframe width="100%" height="100%" src="https://www.youtube.com/embed/CRRlbK5w8AE?si=MJ-KRN8i6fKAoAhJ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe> '),
		('https://moviesapi.ir/images/tt0253474_poster.jpg ','The Pianist ','2022 ','Biography,Drama,History ',8.2 ,'150 min ','https://moviesapi.ir/images/tt0253474_screenshot1.jpg ','https://moviesapi.ir/images/tt0253474_screenshot2.jpg ','Adrien Brody, Emilia Fox, Michal Zebrowski, Ed Stoppard ','A Polish Jewish musician struggles to survive the destruction of the Warsaw ghetto of World War II. ','<iframe width="100%" height="100%" src="https://www.youtube.com/embed/BFwGqLa_oAo?si=DwcWN3wz3tXOK-B7" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe> '),
		('https://moviesapi.ir/images/tt0407887_poster.jpg ','The Departed ','2023 ','Crime,Drama,Thriller ',8.6 ,'151 min ','https://moviesapi.ir/images/tt0407887_screenshot1.jpg ','https://moviesapi.ir/images/tt0407887_screenshot2.jpg ','Leonardo DiCaprio, Matt Damon, Jack Nicholson, Mark Wahlberg ','An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston. ','<iframe width="100%" height="100%" src="https://www.youtube.com/embed/r-MiSNsCdQ4?si=gGDk-rVN4pOQgSDG" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe> '),
		('https://moviesapi.ir/images/tt0088763_poster.jpg ','Back to the Future ','2017 ','Adventure,Comedy,Sci-Fi ',8.6 ,'116 min ','https://moviesapi.ir/images/tt0088763_screenshot1.jpg ','https://moviesapi.ir/images/tt0088763_screenshot2.jpg ','Michael J. Fox, Christopher Lloyd, Lea Thompson, Crispin Glover ','Marty McFly, a 17-year-old high school student, is accidentally sent 30 years into the past in a time-traveling DeLorean invented by his close friend, the maverick scientist Doc Brown. ','<iframe width="100%" height="100%" src="https://www.youtube.com/embed/qvsgGtivCgs?si=t-nFzHO35jKjHbrS" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe> '),
		('https://moviesapi.ir/images/tt0172495_poster.jpg ','Gladiator ','2020 ','Action,Adventure,Drama ',8.4 ,'155 min ','https://moviesapi.ir/images/tt0172495_screenshot1.jpg ','https://moviesapi.ir/images/tt0172495_screenshot2.jpg ','Russell Crowe, Joaquin Phoenix, Connie Nielsen, Oliver Reed ','When a Roman general is betrayed and his family murdered by an emperors corrupt son, he comes to Rome as a gladiator to seek revenge. ','<iframe width="100%" height="100%" src="https://www.youtube.com/embed/P5ieIbInFpg?si=xRcsF_w12gMaT0fF" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe> '),
		('https://m.media-amazon.com/images/I/710ievVCTTL._SL1100_.jpg','Sprited Away','2001', 'Animation,Family,Adventure',8.6,'125min', 'https://m.media-amazon.com/images/M/MV5BMjE1Mjk2MTcwNV5BMl5BanBnXkFtZTgwNTc1MTMyMDE@._V1_.jpg','https://s3.amazonaws.com/thumbnails.thecrimson.com/photos/2021/07/30/030310_1350926.png.1500x1005_q95_crop-smart_upscale.png','Hayao Miyazaki, Toshio Suzuki', 'Spirited Away tells the story of Chihiro "Sen" Ogino, a ten-year-old girl who, while moving to a new neighborhood, inadvertently enters the world of kami (spirits of Japanese Shinto folklore).[7] After her parents are turned into pigs by the witch Yubaba, Chihiro takes a job working in Yubabas bathhouse to find a way to free herself and her parents and return to the human world', '<iframe width="100%" height="100%" src="https://www.youtube.com/embed/ByXuk9QqQkk?si=rmGgjSeKGehzfIBV" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>');
		
	SELECT * FROM Movies
	select * From UserLike


insert into users(username,password)
values ('test','test')

SELECT * FROM Movies WHERE mId = 1